on:
  push:
    branches:
      - master
name: Deploy build to gh-pages
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: dist